[project]
name = "rental-market-intelligence-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.11.12",
    "dbt-snowflake>=1.11.6",
    "pandas>=3.0.3",
    "plotly>=6.9.0",
    "snowflake-connector-python>=4.7.1",
    "streamlit>=1.60.0",
]
